### ISSUE TITLE
Failing on re.search

### ISSUE THREAD

**Issue by bryanroscoe** [bryanroscoe/aqicn#2]
Scraping Nishisanjocho, Omura, Nagasaki (大村大気測定局大村市) 175 of 3417 [32.9134973, 129.9602632] 4709
Nishisanjocho, Omura, Nagasaki (大村大気測定局大村市) encountered an error: Traceback (most recent call last):
  File "./aqicn.py", line 95, in handleCity
    newTime = re.search( "(?<=Updated on )._$",soup.find(text=re.compile("(?<=Updated on )._?"))).group(0)
  File "/usr/local/lib/python3.4/re.py", line 166, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer

**Comment by bryanroscoe** [comment]
Should be resolved
